final_forms = {'a': ['a', 'd', 'h', 'i', 'k', 'l', 'm', 'n', 'p', 'r', 't', 'u', 'x'],
               'c': ['c', 'e'],
               'b': ['b', 'v', 'w'],
               'o': ['o'],
               'g': ['g', 'j', 'Z', 'Y', 'J'],
               'f': ['f', 's'],
               'q': ['q'],
               'A': ['A', 'H'],
               'L': ['L', 'Q'],
               'K': ['K', 'R', 'X'],
               'M': ['M'],
               'D': ['D']}

initial_forms = {'a': ['a', 'd', 'g', 'q'],
                 'b': ['b', 'f', 'h', 'k', 'l'],
                 'c': ['c'],
                 'e': ['e'],
                 'i': ['i', 'j', 'u', 't', 'w'],
                 'm': ['m', 'n', 'v', 'x', 'y', 'z'],
                 'o': ['o'],
                 'p': ['p', 'r', 's']}
                 
changable_inital_forms = {'a': False,
                          'b': True,
                          'c': False,
                          'e': True,
                          'i': False,
                          'm': False,
                          'o': False,
                          'p': True}